//
// Created by ToBy_RedStones on 14/12/2023.
//

#ifndef PRIMALITYTESTS_MILLERRABINPRIMALITYTEST_H
#define PRIMALITYTESTS_MILLERRABINPRIMALITYTEST_H
int MillerRabinPrimalityTest(int n, int by);
#endif //PRIMALITYTESTS_MILLERRABINPRIMALITYTEST_H
