//
// Created by ToBy_RedStones on 14/12/2023.
//

#ifndef PRIMALITYTESTS_NONTRIVIALSQUAREROOTTEST_H
#define PRIMALITYTESTS_NONTRIVIALSQUAREROOTTEST_H
int nontrivialSquareRootTest(int n);
#endif //PRIMALITYTESTS_NONTRIVIALSQUAREROOTTEST_H
